parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/images'

framework:
    secret: "%env(APP_SECRET)%"
    session: true
    assets:
        packages:
            uploads:
                base_path: /uploads

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
